#!/bin/bash

set -eou pipefail

date

terminus auth:login --email=sarah@sarahgerman.com

#SITELIST="sites-test.txt"
SITELIST="sites.txt"

echo "[notice] Running core updates..."
terminus site:mass-update:apply < "$SITELIST"