#!/bin/bash

set -eou pipefail

date

#SITELIST="sites-test.txt"
SITELIST="sites.txt"

# Make sure the dev env is clean.
# Requires Sarah's Terminus fork to add the "uncommitted_changes" field.
# @TODO split this into a separate script? should do this before updating plugins too.
while read -r SITE_UUID; do

    # @todo check if there are updates first. if not, skip
    ENV_INFO="$(terminus env:info --fields=uncommitted_changes,connection_mode --format=json "${SITE_UUID}".dev)"
    DIRTY=$(jq .'uncommitted_changes' <<< "${ENV_INFO}" )
    CONNECTION_MODE=$(jq -r .'connection_mode' <<< "${ENV_INFO}" )

    if [[ "$DIRTY" == "true" ]]; then
        echo -e "[warning] Site $SITE_UUID has uncommitted code on Dev. Remediate before proceededing."
    
    elif [[ "$CONNECTION_MODE" == "sftp" ]]; then
        # SFTP mode without uncommitted code is OK, 
        # but we still need to flip it to Git to proceed.
        echo "[notice] Changing connection setting for ${SITE_UUID}"
        terminus connection:set "${SITE_UUID}".dev git
    fi

done < $SITELIST

echo "[notice] Running core updates..."
terminus site:mass-update:apply < "$SITELIST"