#!/bin/bash

set -eou pipefail

SITENAME=${1}
CONFIG_FILE="backstop-config/${SITENAME}-backstop.json"

# Create a multidev of Live.
terminus multidev:create ${SITENAME}.live vrt

# Build a reference file and run VRT.
backstop reference --configPath=${CONFIG_FILE}
backstop test --configPath=${CONFIG_FILE}

# Remove the multidev.
# @TODO It'd be better to just re-use these and refresh them.
terminus multidev:delete ${SITENAME}.vrt