#!/bin/bash

set -eou pipefail

SITELIST="sites-test.txt"
#SITELIST="sites.txt"

MONTH="2021-01" # @todo arrrrg

# Loop through all sites on the list.
while IFS='' read -r SITENAME || [ -n "${SITENAME}" ]; do

    # Copy the report template.
    REPORT_DIR=reports/output/$SITENAME-$MONTH
    mkdir "${REPORT_DIR}"
    REPORT_FILE="${REPORT_DIR}/index.html"
    cp reports/template.html "${REPORT_FILE}"

    #sed -e "s/<!--sitename-->/${SITENAME}/g" reports/template.html > $REPORT_FILE

    # Get code updates from this month.
    # @todo these timestamps are in UTC. 
    # Commits made late in the day on the last day of the month aren't going to show up here.
    COMMITS="$(terminus env:code-log --format=json "${SITENAME}".live | jq -c '.[] | select( .datetime | contains('\"$MONTH\"'))')"

    # Health checks.
    #UPTIME= # @todo pull from Pingdom
    # Backups
    # terminus workflow:list catparty --format=json | jq -c '.[] | select(.workflow | contains("Automated backup for the \"live\""))'
    #BACKUPS_ENABLED= (True if any returned)
    #LATEST_BACKUP= (get top entry)

    #EXPLOITS=$(terminus wp launchcheck secure)

    # Traffic report.
    #VISITS
    #404s/Broken Links
    #linkchecker https://www.ccrp.org/ --ignore-url="/wp-json/" --file-output=csv
    #awk '($9 ~ /404/)' nginx-access.log* | awk '{print $7}' | sort | uniq -c | sort -rn > 404s.txt

    # PAGES_SERVED
    #terminus env:metrics ccrp-org.live --period=month
    #PLAN_INFO

    # IPS BLOCKED? -- use nginx-log-analyzer
    # fix log formatter, its showing internal IPs

    # Site performance
    # Lighthouse report

    # Build JSON files.
    # @todo building a single file would be nicer client-side probs
    mkdir "${REPORT_DIR}"/json
    echo "${COMMITS}" | jq -s '.' > "${REPORT_DIR}"/json/updates.json

done < $SITELIST
