#!/bin/bash

set -eou pipefail

TAG="testing"
#TAG="maintenance"

REPORT_PATH="/Users/sarahgerman/Sites/site-report-card-mvp/reports"

MONTH="2021-01" # @todo arg

ORG_UUID=$(jq -r '.orgID' config.json) 
SITES=$(terminus org:site:list --field=name --tag=${TAG} --filter="framework=wordpress" -- $ORG_UUID)

# Loop through all sites on the list.
while read -r SITENAME; do

    # Create the report page.
    REPORT_FILE="reports/${SITENAME}-${MONTH}.html"
    cp reports/template.html $REPORT_FILE
    sed -e "s/<!--sitename-->/${SITENAME}/g" reports/template.html > $REPORT_FILE

    # @todo clone if it doesn't exist (connection:info for the URL)
    #cd /Users/sarahgerman/Sites/$SITENAME && git fetch origin

    # Get the update list from Git.
    #TAGS=$(git tag -l --format='%(refname:short):%(creatordate:short)' | grep pantheon_live | grep $MONTH)
    #for TAG in $TAGS; do

        #${REPORT_PATH}/${SITENAME}-git-log-${DATE}.txt
    #done

    # Health checks.
    #BACKUPS_ENABLED=1 # @todo verify this w/ terminus backup:automatic:info
    #LAST_BACKUP=$(terminus backup:list $SITENAME.live)
    #UPTIME= # @todo pull from Pingdom
    #EXPLOITS=$(terminus wp launchcheck exploits)

    # Traffic report.
    #VISITS
    #404s/Broken Links
    #PAGES_SERVED
    #PLAN_INFO
    #IPS BLOCKED?

    # Site performance
    # Lighthouse report

done <<< "$SITES"