#!/bin/bash

set -eou pipefail

#SITELIST="sites-test.txt"
SITELIST="sites.txt"

# @TODO Throw light traffic at the Test site and check for errors/500s

# Make a backup and deploy to Live
# @todo better deploy note
# @todo skip if there isn't anything to deploy
while IFS='' read -r SITENAME || [ -n "${SITENAME}" ]; do
    echo "Deploying $SITENAME..."
    terminus backup:create "${SITENAME}".live --element=db
    terminus env:deploy --note="Maintenance updates." -- "${SITENAME}".live
    terminus wp "${SITENAME}".live -- core update-db < /dev/null
    terminus env:clear-cache "${SITENAME}".live
done < $SITELIST

# @todo handling for cases where there are no updates.
echo "[notice] Go check the Live sites: "
while IFS='' read -r SITENAME || [ -n "${SITENAME}" ]; do
    echo -e "- https://live-${SITENAME}.pantheonsite.io"
done < $SITELIST
