#!/bin/bash

set -eou pipefail

#TAG="maintenance"
TAG="testing"

ORG_UUID=$(jq -r '.orgID' config.json) 
SITES=$(terminus org:site:list --field=name --tag=${TAG} --filter="framework=wordpress" -- $ORG_UUID)

# @TODO Incorporate AutoPilot/VRT
# @TODO Throw light traffic at the Test site and check for errors/500s

# Make a backup and deploy to Live
# @todo better deploy note
# @todo skip if there isn't anything to deploy
while read -r SITENAME; do
    echo "Deploying $SITENAME..."
    terminus backup:create "${SITENAME}".live --element=db
    terminus env:deploy --note="Code updates." -- "${SITENAME}".live
    terminus wp "${SITENAME}".live -- core update-db
    terminus env:clear-cache "${SITENAME}".live
done <<< "$SITES"

# @todo handling for cases where there are no updates.
echo "[notice] Go check the Live sites: "
while read -r SITENAME; do
    echo -e "- https://live-${SITENAME}.pantheonsite.io"
done <<< "$SITES"